# Generated by Django 4.2.23 on 2025-11-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('number', models.CharField(max_length=11, null=True, unique=True, verbose_name='电话号码')),
                ('email', models.EmailField(max_length=128, null=True, unique=True, verbose_name='邮箱')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '禁用')], default='active', max_length=10, verbose_name='状态')),
                ('sex', models.CharField(choices=[('boy', '男'), ('girl', '女'), ('notall', '保密')], default='notall', max_length=10, verbose_name='性别')),
                ('avatar', models.CharField(max_length=256, null=True, verbose_name='头像')),
                ('introduce', models.CharField(default='此人很懒,未留下任何简介~', max_length=256, verbose_name='简介')),
                ('usertype', models.CharField(choices=[('head', '站长'), ('general', '普通用户')], default='general', max_length=10, verbose_name='用户类型')),
                ('register', models.DateTimeField(verbose_name='注册时间')),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
