# Generated by Django 4.2.23 on 2026-03-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='userName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sex',
            new_name='userSex',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usertype',
            new_name='userType',
        ),
    ]
