# Generated by Django 4.2.23 on 2025-11-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('articleid', models.IntegerField(verbose_name='文章id')),
                ('authorid', models.IntegerField(verbose_name='评论作者的id')),
                ('content', models.CharField(max_length=200, verbose_name='评论内容')),
                ('fatherid', models.IntegerField(verbose_name='父评论id')),
                ('floorcommentid', models.IntegerField(verbose_name='一级评论id')),
                ('time', models.DateField(verbose_name='评论时间')),
            ],
        ),
    ]
