# Generated by Django 4.2.23 on 2025-11-13 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, unique=True, verbose_name='分类名称')),
                ('desc', models.CharField(max_length=128, null=True, verbose_name='分类描述')),
                ('priority', models.IntegerField(verbose_name='分类优先级')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleLabel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, verbose_name='文章标签')),
                ('desc', models.CharField(max_length=128, null=True, verbose_name='标签描述')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='categorie.articletype', verbose_name='所属类型')),
            ],
        ),
    ]
