# Generated by Django 4.2.23 on 2026-03-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='网站标题')),
                ('poem', models.CharField(max_length=128, verbose_name='诗句')),
                ('author', models.CharField(max_length=32, verbose_name='网站作者')),
                ('recordNumber', models.CharField(max_length=128, verbose_name='备案号')),
                ('email', models.CharField(max_length=32, verbose_name='联系邮箱')),
                ('copyrightInformation', models.CharField(max_length=128, verbose_name='版权信息')),
                ('backgroundImg', models.CharField(max_length=128, verbose_name='背景图片')),
            ],
        ),
    ]
