# Generated by Django 4.2.23 on 2026-04-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebViews',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=32, verbose_name='访问ip')),
                ('latestTime', models.DateTimeField(verbose_name='最近一次访问网站的时间')),
                ('count', models.IntegerField(verbose_name='该ip访问次数')),
            ],
        ),
    ]
