# Generated by Django 4.2.23 on 2026-04-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_webviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webviews',
            name='latestTime',
            field=models.DateTimeField(auto_now=True, verbose_name='最近一次访问网站的时间'),
        ),
    ]
