# Generated by Django 4.2.23 on 2026-04-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_webviews_latesttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webviews',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
