# Generated by Django 4.2.23 on 2025-11-13 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=32, verbose_name='文章作者')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='文章标题')),
                ('limit', models.CharField(max_length=16, verbose_name='文章权限')),
                ('pageviews', models.IntegerField(default=0, verbose_name='浏览量')),
                ('cover', models.URLField(null=True, verbose_name='文章封面')),
                ('show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('comment', models.BooleanField(default=True, verbose_name='是否评论')),
                ('recommend', models.BooleanField(default=True, verbose_name='是否推荐')),
                ('comments', models.IntegerField(default=0, verbose_name='评论数')),
                ('createtime', models.DateTimeField(verbose_name='创建时间')),
                ('finalltime', models.DateTimeField(null=True, verbose_name='最终修改时间')),
                ('text', models.TextField(verbose_name='文章内容')),
                ('label', models.ManyToManyField(related_name='labels', to='categorie.articlelabel', verbose_name='文章标签')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='categorie.articletype', verbose_name='文章类型')),
            ],
        ),
    ]
