# Generated by Django 5.2.9 on 2026-05-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlemessage",
            name="abstract",
            field=models.CharField(default="", max_length=500, verbose_name="文章摘要"),
        ),
    ]
